### PR TITLE
Added support for class based models with inheritance hierarchies

### PR DESCRIPTION
**Pull request by IanKeen**
-Moved the Mirror based serialisation to a `Mirror` extension to make it easier to traverse the inheritance chain for classes
-Duplicated the existing struct test types into class based representations with some inheritance sprinkled in
-Duplicated the relevant struct tests to also test the class models

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! I've been meaning to add class support into the todo list, and now it's set! I'll get this pulled in soon.

**Comment by IanKeen** [comment]
No problem mate! :+1: :smile:

**Comment by nickoneill** [comment]
This looks great, almost ready to pull it in. Just one thing I'm confused about: was there an issue resolved with the use of `EmptyWarehouse`? What's the thinking there?

**Comment by IanKeen** [comment]
That was basically just the quickest way to get the classes up and running due to the fact that the warehouse constructor was required meaning the convenience constructor _must_ chain onto it... so because im supplying the property values I just wanna pass an empty warehouse rather than constructing one

If there is a simpler method or a fast way I can build up a 'proper' warehouse let me know and I'm happy to update.

**Comment by nickoneill** [comment]
OK, I get it now. It feels a bit weird but I think it's a good start, I don't have any other immediate ideas for how to make it simpler for inheritance.

I'll pull this in now. Can you throw together a section of the readme to describe using Pantry with class inheritance?

**Pull request merged**
