### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by andreyz**
Migrated to Swift 3
- to be able to handle nil value in Swift types, switched to JSONSerialization
- explicitly create NSNull in toDictionary for nil optional values
- use Any instead of AnyObject

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks for your work here! I'll pull this in shortly.

**Comment by mickyzinho** [comment]
Any news on when this will get merged?

**Comment by codeOfRobin** [comment]
+1 . Any news on this @nickoneill  ?

**Comment by nickoneill** [comment]
Thanks for waiting friends, this is in master / 0.3 now

**Pull request merged**
