### PR TITLE
Implement in-memory only mode usefull for testing

### PR DESCRIPTION
**Pull request by litso**
Support for in-memory mode to facilitate unit tests, similar to how Realm does it. See MemoryTests.swift for example usage.

### CODE REVIEW

**Comment by nickoneill** [comment]
Awesome @litso, this sets the stage for a better-than-JSON warehouse option as well. Thanks! I'll review and merge this in the next day or two.

**Comment by litso** [comment]
@nickoneill Sounds good! Also cleaned up the project file a bit import the framework instead of just compiling the sources

**Comment by nickoneill** [comment]
Merged with some new optional tests and pulled in. Thanks for this!

**Comment by litso** [comment]
@nickoneill happy to help out!

**Pull request merged**
