### PR TITLE
Support for Enums with raw types

### PR DESCRIPTION
**Pull request by litso**
Added a protocol to Storable so that raw type enums can be easily supported.

### CODE REVIEW

**Comment by nickoneill** [comment]
Missed the new travis config by 3 minutes! I'll check this out tomorrow and we'll get this in.

Thanks! :+1:

**Comment by nickoneill** [comment]
Awesome, this is really great.

One thing:
* Let's add tests for other raw value types, `String` at the very least. I always use either `String` or `Int` raw values, is there a common case for another one of our default types?

And some minor stuff:
* Instead of forcing the `cases` property to unwrap from the `TestStruct` warehouse, let's provide a default - `Case3` for example - that we don't use for any other purpose. I want to encourage users to provide a default, not crash.
* In `testEnumStorable`, `unpackedNested` should just be `unpacked` or `unpackedEnum`
* The same `testEnumStorable` test should test against `TestEnum.Case1`, not `first`
* Indicate support for enums on the readme (I can take care of this)

**Comment by burntheroad** [comment]
@nickoneill how can I help with this PR? Should I fork `litso:enum-support`?

**Comment by nickoneill** [comment]
Hey @burntheroad, for sure you can finish this off. Fork that branch and submit a new PR with the changes.

**Comment by litso** [comment]
Any help is appreciated but I can probably fix up the tests today

**Comment by litso** [comment]
@nickoneill Thanks to @burntheroad this should be good to go

**Comment by nickoneill** [comment]
Awesome, thanks to both of you!

**Pull request merged**
