### PR TITLE
Local cache for Optional type value

### PR DESCRIPTION
**Pull request by jhihguan**
When struct has Optional type value like `let name: String?`
and if the field does has value, it won’t actually cache to local

The code fix it

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! Can you add tests for these results?

**Comment by jhihguan** [comment]
Sure!

**Comment by jhihguan** [comment]
Hi, I've added some test data and it works fine.

But when I testing for optional array of Storable, it won't work as expected
Right now I just remove the test code for optional Array, will open an issue to discuss it

**Comment by nickoneill** [comment]
Please add that failing test! I'd like to further investigate what's happening there.

**Comment by jhihguan** [comment]
I've added the failing test.

It's because the toDictionary will first check if it's Collection type, but for Optional type the code won't unwrap the value(which is Collection type) first than walk through combine

**Pull request merged**
