### PR TITLE
Add tests for upgrading struct

### LINKED ISSUE #7: Add tests for "upgrading" a struct
- [ ] case where a struct has a field added, it should be the default
- [ ] case where a struct has a field removed, it should not fail

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Fixes #7

### CODE REVIEW

**Comment by nickoneill** [comment]
Thanks! This is exactly what I was thinking of!

It looks like the test function names are reversed?

**Comment by aciidb0mb3r** [comment]
something like `testStructUpgradedPropertyAdded` then?

**Comment by nickoneill** [comment]
The current names are fine, but it looks like `func testUpgradedStructFieldAdded` is where you are using `BasicUpgradedFieldRemoved` struct, same for the opposite case.

**Comment by aciidb0mb3r** [comment]
Oh 😳
Silly mistake. will fix.

On Friday 22 January 2016, nickoneill <notifications@github.com> wrote:

> The current names are fine, but it looks like func
> testUpgradedStructFieldAdded is where you are using
> BasicUpgradedFieldRemoved struct, same for the opposite case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickoneill/Pantry/pull/26#issuecomment-173967574>.
>


-- 
Ankit

**Comment by aciidb0mb3r** [comment]
Fixed

**Comment by nickoneill** [comment]
Thanks! Will pull this in soon.

**Pull request merged**
