### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by aciidb0mb3r**
Sample usage package via my fork :
https://github.com/aciidb0mb3r/Pantrie

This will start working on this repo by creating tag from master after this PR is merged

### CODE REVIEW

**Comment by nickoneill** [comment]
Awesome! Let me review a bit more about the package manager... I may merge this into a package manager branch for now, not sure how likely things are to change at the moment.

**Comment by aciidb0mb3r** [comment]
It won't "break" the project if swiftpm support is added right now but package might get broken at user side if some breaking change is released on swiftpm though thats unlikely because current swiftpm configurations are very minimal on Pantry.

**Comment by nickoneill** [comment]
Can you rebase this on the current master and PR to the `swiftpm` branch for now? I'd like to do more experimentation on this before pulling it into master.

I'm actually not sure if the package manager can specify branches to grab dependencies from yet but if not, that seems like a nice place to get started contributing to swift :)

**Comment by nickoneill** [comment]
This was pulled in with #31

**Comment by aciidb0mb3r** [comment]
done.
Swiftpm doesn't have feature to grab from a branch right now but I've a [proposal](https://lists.swift.org/pipermail/swift-build-dev/Week-of-Mon-20151221/000110.html) going on there which will support custom branches.

**Comment by nickoneill** [comment]
Awesome!

**Pull request closed without merging**
